name: Deploy Application
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install project dependencies
      run: npm install
      
    - name: Build Compute@Edge Package
      uses: fastly/compute-actions/build@main
      with:
        verbose: true # optionally enables verbose output, defaults to false
        skip_verification: true # optional, defaults to false

    - name: Deploy to Compute@Edge
      uses: fastly/compute-actions@main
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
